from extract import data
import pandas as pd
from datetime import datetime
import os

# Asegura que la carpeta exista
os.makedirs("data_output", exist_ok=True)

# Extraemos los datos necesarios
timestamp = data.get("timestamp")
position = data.get("iss_position", {})

# Creamos un DataFrame con los valores deseados
df = pd.DataFrame([{
    "datetime": datetime.utcfromtimestamp(timestamp),
    "latitude": float(position.get("latitude", 0)),
    "longitude": float(position.get("longitude", 0))
}])

# Guardamos el DataFrame transformado
df.to_csv("data_output/transformed_data.csv", index=False)

# Mostramos el resultado por consola
print(df.head())

# # Rename columns for better clarity
# df.columns = ['risk_value', 'date']

# # Convert the 'date' column to datetime format for temporal analysis
# df['date'] = pd.to_datetime(df['date'])

# # Sort the data by date to ensure chronological order
# df = df.sort_values(by='date').reset_index(drop=True)

# # Calculate the daily variation in the risk value
# df['daily_variation'] = df['risk_value'].diff()

# # Add a column to identify the trend: increase, decrease, or no change
# df['trend'] = df['daily_variation'].apply(lambda x: 'Increase' if x > 0 else 'Decrease' if x < 0 else 'No Change')

# # Remove any null values generated by calculations
# df_clean = df.dropna()

# # Display the transformed DataFrame
# print(df_clean.head())

# # Save the transformed DataFrame for the load.py script
# df_clean.to_csv("data_output/transformed_data.csv", index=False)
