from extract import df
import pandas as pd

# # Rename columns for better clarity
# df.columns = ['risk_value', 'date']

# # Convert the 'date' column to datetime format for temporal analysis
# df['date'] = pd.to_datetime(df['date'])

# # Sort the data by date to ensure chronological order
# df = df.sort_values(by='date').reset_index(drop=True)

# # Calculate the daily variation in the risk value
# df['daily_variation'] = df['risk_value'].diff()

# # Add a column to identify the trend: increase, decrease, or no change
# df['trend'] = df['daily_variation'].apply(lambda x: 'Increase' if x > 0 else 'Decrease' if x < 0 else 'No Change')

# # Remove any null values generated by calculations
# df_clean = df.dropna()

# # Display the transformed DataFrame
# print(df_clean.head())

# # Save the transformed DataFrame for the load.py script
# df_clean.to_csv("data_output/transformed_data.csv", index=False)

#####################
# datos = {
#     "timestamp": [data["timestamp"]],
#     "latitude": [data["iss_position"]["latitude"]],
#     "longitude": [data["iss_position"]["longitude"]],
#     "message": [data["message"]]
# }

# # Crear DataFrame crudo
# df = pd.DataFrame(datos)

# # Transformar: convertir timestamp a fecha legible y renombrar columnas
# df["timestamp"] = pd.to_datetime(df["timestamp"], unit='s')
# df = df.rename(columns={
#     "timestamp": "Fecha y hora (UTC)",
#     "latitude": "Latitud",
#     "longitude": "Longitud",
#     "message": "Mensaje"
# })

# # Exportar a CSV
# df.to_csv("data_output/transformed_data.csv", index=False, encoding='utf-8-sig')
# print("CSV exportado: transformed_data.csv")
###################################

import pandas as pd
from extract import obtener_datos  # <- Importamos la función, no el df

# Llamamos la función para obtener los datos
df = obtener_datos()

# Validamos que tenga datos
if df.empty:
    print("❌ No se encontraron datos para transformar.")
else:
    # Transformar timestamp a formato legible
    df["timestamp"] = pd.to_datetime(df["timestamp"], unit='s')
    df = df.rename(columns={
        "timestamp": "Fecha y hora (UTC)",
        "latitude": "Latitud",
        "longitude": "Longitud",
        "message": "Mensaje"
    })

    # Exportar a CSV
    df.to_csv("data_output/transformed_data.csv", index=False, encoding='utf-8-sig')
    print("✅ CSV exportado: data_output/transformed_data.csv")